version: "0.2"
ignorePaths:
  - "**/obj/**"
  - "**/.vs/**"
  - "**/bin/**"
dictionaryDefinitions:
  - name: clipboard-monitor
    path: ./.github/config/clipboard-monitor.dict
    addWords: true
dictionaries:
  - clipboard-monitor
words: []
ignoreWords: []
import: []
